# Generated by Django 5.0.2 on 2024-02-17 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('36f6f12d-c435-47a5-b201-b5c7064ac4c5')),
        ),
    ]
