# Generated by Django 5.0.2 on 2024-02-17 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resume_job_location_alter_resume_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.AlterField(
            model_name='resume',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c31b02f2-52ff-419e-b33b-d6966dda993e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
