# Generated by Django 5.0.2 on 2024-02-17 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_resume_id_alter_resume_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
